checks:
  addAllBuiltIn: true
  ignorePaths:
    - "helm/tempo/charts/tempo-distributed/charts/**"
    - "helm/tempo/charts/tempo-distributed/templates/**"
    - "helm/tempo/charts/tempo-vulture/templates/**"
  exclude:
    - "unset-cpu-requirements"
    - "unset-memory-requirements"
    - "dangling-service"
    - "required-label-owner"
    - "use-namespace"
    - "required-annotation-email"
    - "non-isolated-pod"
    - "no-rolling-update-strategy"
    - "no-node-affinity"
    - "no-liveness-probe"
    - "minimum-three-replicas"
    - "read-secret-from-env-var"
    - "restart-policy"
    - "no-readiness-probe"
    - "run-as-non-root"
    - "no-read-only-root-fs"
    - "dnsconfig-options"
    - "access-to-secrets"
    - "access-to-create-pods"
    - "latest-tag"
    - "default-service-account"
